/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

interface SkipWaitingMessage {
  type: 'SKIP_WAITING';
}

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Handle activation
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Handle messages from clients
self.addEventListener('message', (event) => {
  const data = event.data as SkipWaitingMessage | null;
  if (data?.type === 'SKIP_WAITING') {
    void self.skipWaiting();
  }
});
